### ISSUE TITLE
Project Demo Checklist

### ISSUE THREAD

**Issue by Mikumiku747** [Mikumiku747/lqip#12]
I thought I'd make a list if the parts we need working in order to get the demo running next Monday, when you get your part done, just check it off the list. If you're having any problems, send a message and somebody can probably take over for you. :)

 - [x] Argument Parser
 - [x] Can accept 1 image from the command line
 - [x] Image decoder for at least 1 format
 - [x] Image resizing algorithm (any kind, just has to produce an approximate resize)
 - [x] Base64 Encoder for resized image
 - [ ] YAML file generator for a single base64 image string
 - [x] Basic string encryption (any algorithm, as long as it somewhat obscures the data)

Please add thoughts, and if you can, try to finish these by saturday midnight or sunday midday so we can integrate them all into the program.

**Comment by Mikumiku747** [comment]
OK, demo day passed, and I actually did manage to get it working before the end of the lab. So now, I'll probably make a checklist where everyone can put their goals for their individual modules, as well as the program in general. Thanks for bearing with me :smile:
